In [6]:
import numpy as np 
new_array=np.array([2,5,3,6,8])
print(f'NumPy Array:\n{new_array}')

list1 = new_array.tolist()
print(f'List: {list1}')

NumPy Array:
[2 5 3 6 8]
List: [2, 5, 3, 6, 8]


In [9]:
import numpy as np 
array = np.arange(6).reshape(2,3)
print("Original : ", array)
result = np.trace(array)
print("output : ", result)


Original :  [[0 1 2]
 [3 4 5]]
output :  4


In [17]:
import numpy as np
x = np.array([[0, 10, 20], [20, 30, 40]])
print("array: ")
print(x)
print("Values bigger than 10 =", x[x>10])
print("Their indices are ", np.nonzero(x > 10))
    

array: 
[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


In [1]:
import numpy as np 
A= np.array([0, 10, 20], dtype=np.float64)
B= np.array([0, 10, 20], dtype=np.float64)
C= A + B
print("The new array is : ", C)

The new array is :  [ 0. 20. 40.]


In [2]:
import numpy as np
print("original matrix:")
X = np.random.rand(5, 10)
print(X)
print("subtract the mean of each row of the said matrix:")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

original matrix:
[[8.81381303e-01 8.05414914e-01 2.66974042e-02 3.10952179e-01
  8.33644063e-01 5.29149825e-01 6.45310802e-02 9.80091947e-01
  9.64320919e-03 7.13952401e-01]
 [6.58811799e-01 5.96866669e-02 3.57652213e-01 5.06315774e-01
  3.54104394e-01 2.40762921e-01 3.95300686e-01 7.56021257e-01
  4.76811968e-01 7.12857006e-01]
 [4.80562216e-01 6.24310745e-01 7.47126326e-02 9.98819516e-01
  1.27465033e-02 8.84526970e-01 7.97330978e-01 3.23784083e-02
  4.36275918e-01 6.31805677e-02]
 [4.63359010e-01 3.30492786e-02 4.12032432e-01 9.55634120e-01
  7.09405807e-01 1.77907437e-01 1.76840202e-01 6.69329980e-01
  3.93602375e-01 8.34407931e-02]
 [9.98228793e-05 3.67048033e-01 6.64444212e-01 7.94152196e-01
  3.51536098e-01 5.53853627e-01 5.66084497e-01 6.65628771e-01
  6.31596667e-01 6.45565792e-01]]
subtract the mean of each row of the said matrix:
[[ 0.36583547  0.28986908 -0.48884843 -0.20459365  0.31809823  0.01360399
  -0.45101475  0.46454611 -0.50590262  0.19840657]
 [ 0.20697933 -0.39214